"""
display.py — Colors, printing, and terminal formatting.
"""


class C:
    BOLD    = '\033[1m'
    DIM     = '\033[2m'
    RESET   = '\033[0m'
    RED     = '\033[91m'
    GREEN   = '\033[92m'
    YELLOW  = '\033[93m'
    BLUE    = '\033[94m'
    MAGENTA = '\033[95m'
    CYAN    = '\033[96m'


def print_usage():
    print(f"""
  {C.BOLD}{C.CYAN}mapi{C.RESET} — Find the exact API call you need

  {C.BOLD}Usage:{C.RESET}
    mapi -<language> <api> <what you need>

  {C.BOLD}Examples:{C.RESET}
    mapi -python gemini generate text
    mapi -javascript googlemaps get directions
    mapi -curl gemini chat conversation
    mapi -rust googlemaps geocode address

  {C.BOLD}Test with your API key:{C.RESET}
    mapi test api_key="YOUR_REAL_KEY"

  {C.BOLD}Available APIs:{C.RESET}
    gemini        Google Gemini (text generation, vision, embeddings)
    googlemaps    Google Maps (geocoding, directions, places, distance)

  {C.BOLD}Any language works:{C.RESET} -python, -javascript, -curl, -rust, -go, -java, etc.
""")


def print_result(code, verification, language, from_cache):
    """Print the generated code with verification badge."""
    if from_cache:
        print(f"\n  {C.GREEN}⚡ Cache hit — instant result{C.RESET}")
    else:
        print(f"\n  {C.BLUE}🤖 Generated by Groq AI{C.RESET}")

    v = verification
    if v.get('verified'):
        status = v['status']
        msg = v['message']
        if status in (401, 403):
            print(f"  {C.GREEN}✓ Endpoint verified{C.RESET} ({status}: API key required)")
            print(f"  {C.DIM}API says: \"{msg}\"{C.RESET}")
            print(f"  {C.DIM}→ Endpoint is real. Paste your key to use it.{C.RESET}")
        elif status == 400:
            print(f"  {C.GREEN}✓ Endpoint verified{C.RESET} ({status}: needs valid request body)")
            print(f"  {C.DIM}API says: \"{msg}\"{C.RESET}")
        elif status == 200:
            print(f"  {C.GREEN}✓ Endpoint verified (200 OK){C.RESET}")
        else:
            print(f"  {C.YELLOW}⚠ Endpoint returned {status}{C.RESET}")
            print(f"  {C.DIM}API says: \"{msg}\"{C.RESET}")
    else:
        print(f"  {C.YELLOW}⚠ Could not verify endpoint{C.RESET}")
        if v.get('message'):
            print(f"  {C.DIM}{v['message']}{C.RESET}")

    print(f"\n  {C.BOLD}── {language} {'─' * (40 - len(language))}{C.RESET}\n")
    for line in code.split('\n'):
        print(f"  {line}")
    print(f"\n  {C.BOLD}{'─' * 44}{C.RESET}")
    print(f"\n  {C.DIM}To test with your real key:{C.RESET}")
    print(f"  {C.CYAN}mapi test api_key=\"YOUR_REAL_KEY\"{C.RESET}\n")